# Generated by Django 3.1.6 on 2021-04-21 06:00

import datetime
from django.db import migrations, models
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210420_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='exam_condition',
            field=models.CharField(default='Available', max_length=10),
        ),
        migrations.AddField(
            model_name='examination',
            name='exam_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(11, 45, 21, 146586)),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_date',
            field=models.DateField(validators=[first_app.models.no_past]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(blank=True, validators=[first_app.models.no_future]),
        ),
    ]
