# Generated by Django 3.1.6 on 2021-04-21 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20210421_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(13, 24, 52, 242331)),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('obj_answer', models.CharField(max_length=255)),
                ('sub_answer', models.TextField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.examination')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.question')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.userprofileinfo')),
            ],
        ),
    ]
