# Generated by Django 3.1.6 on 2021-04-22 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20210421_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='exam_pass',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(0, 37, 17, 135993)),
        ),
    ]
