# Generated by Django 3.1.6 on 2021-04-23 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20210423_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalculateMarks',
            new_name='CalculatedMark',
        ),
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(11, 59, 38, 167160)),
        ),
    ]
