# Generated by Django 3.1.6 on 2021-04-23 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20210423_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(12, 16, 22, 627054)),
        ),
        migrations.DeleteModel(
            name='CalculatedMark',
        ),
    ]
