# Generated by Django 3.1.6 on 2021-04-23 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20210423_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(12, 17, 2, 682735)),
        ),
        migrations.CreateModel(
            name='CalculatedMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('obj_answer', models.CharField(max_length=255)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.examination')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.question')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.userprofileinfo')),
            ],
        ),
    ]
