# Generated by Django 3.1.6 on 2021-04-23 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20210423_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(20, 6, 55, 678598)),
        ),
        migrations.DeleteModel(
            name='FinalResult',
        ),
    ]
