# Generated by Django 3.1.6 on 2021-04-23 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_auto_20210423_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(22, 13, 38, 982155)),
        ),
    ]
