# Generated by Django 3.1.6 on 2021-04-24 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_auto_20210424_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(18, 32, 57, 501185)),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_pass',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
