# Generated by Django 3.1.6 on 2021-04-29 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_auto_20210427_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(11, 15, 34, 919135)),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_exam', to='first_app.examination'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_id', to='first_app.question'),
        ),
    ]
