# Generated by Django 3.1.6 on 2021-04-29 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_auto_20210429_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(12, 0, 43, 398677)),
        ),
    ]
