# Generated by Django 3.1.6 on 2021-04-29 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0033_auto_20210429_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('notification_text', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.course')),
            ],
        ),
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(18, 13, 24, 278406)),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
