# Generated by Django 3.1.6 on 2021-04-29 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_auto_20210429_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.CharField(default='Student', max_length=255),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(0, 59, 6, 977488)),
        ),
    ]
