# Generated by Django 3.1.6 on 2021-05-22 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0035_auto_20210430_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 21, 42, 25, 10776)),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exactTimeStart',
            field=models.TimeField(default=datetime.time(21, 42, 25, 7784)),
        ),
    ]
